stages:
  - build
  - test
#  - quality
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/classes/
    expire_in: 1 day

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn test
  dependencies:
    - build

#quality:
#  stage: quality
#  image: maven:3.9.6-eclipse-temurin-17
#  script:
#    - mvn qulice:check
#  dependencies:
#    - build
#  allow_failure: true

package:
  stage: package
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn package -DskipTests
  dependencies:
    - build
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days