spring.application.name=TP_Architecture

# Resilience4J Retry Configuration
resilience4j.retry.instances.recetteRetry.maxAttempts=3
resilience4j.retry.instances.recetteRetry.waitDuration=1000
resilience4j.retry.instances.recetteRetry.retryExceptions=org.springframework.dao.DataAccessException,java.sql.SQLException
resilience4j.retry.instances.recetteRetry.ignoreExceptions=

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Actuator endpoints pour monitoring Resilience4J et Kafka
management.endpoints.web.exposure.include=health,metrics,retryevents
management.endpoint.health.show-details=always
